### ISSUE TITLE
Black border of icons 

### ISSUE THREAD

**Issue by sijafu** [EliverLara/Nordic#29] opened 2019-06-16 18:40 UTC
Hi, first of all thank You for the work you have done. It is for far best theme I have ever used.
To achieve perfection I need to know how to change two things:
1. How can I remove black border around applets icons? I was checking css files but with no effect, also there are two files gtk.css and gtk-dark.css, which one should I edit?
- https://imgur.com/3VD45Vb.png
2. Sometimes fields in Firefox aren't contrasting with text, any idea how can I solve it?
EDIT: I found out that this is releated to Firefox, it is know issue for 19 years :D

Thank You once again and looking forward to Your reply.

**Comment by EliverLara** [comment] 2019-06-17 14:39
Hi, Could you provide more info about your OS please?

**Comment by sijafu** [comment] 2019-06-17 17:17
Hi, of course:
DISTRIB_ID=ManjaroLinux
DISTRIB_RELEASE=18.0.4
DISTRIB_CODENAME=Illyria
DISTRIB_DESCRIPTION="Manjaro Linux"

$ xfce4-panel --version
xfce4-panel 4.13.5git-44d2d6 (Xfce 4.13)

https://imgur.com/Bmn7DwF.png
https://imgur.com/bN5GUMd.png

Thanks in advance

**Comment by EliverLara** [comment] 2019-06-17 20:22
Thanks for the info, the issue is fixed now!

**Closed** 2019-07-03 18:27 UTC
