### ISSUE TITLE
Xfce 4.18 panel has corruption

### ISSUE THREAD

**Issue by tulliana** [EliverLara/Nordic#246] opened 2022-12-24 23:51 UTC
We see some compatibility issues between Xfce 4.18 stable version and Nordic Theme. For example, there are cosmetic imperfections on the Xfce 4.18 panel as seen in the screenshot below. There are notches on the top of the panel.
![nordic-theme-xfce-panel-4_18](https://user-images.githubusercontent.com/2324162/209453483-ba91cf3d-42e8-431d-98b6-f28054df205d.jpg)

**Comment by 237dmitry** [comment] 2023-01-06 09:28
After the last update the issue is still on. This applies to the whisker's menu text-button on the panel.

Settings:
![prop](https://user-images.githubusercontent.com/78153320/210971196-30db3bb0-1926-4498-bc78-3f95226990c5.png)

Panel button of Whisker Menu:
![wisker](https://user-images.githubusercontent.com/78153320/210971436-1ba44fed-3405-4446-bd45-cf18db1a2f8b.png)

**Comment by tulliana** [comment] 2023-01-06 18:44
There seems to be some improvement, but there are still roughnesses.

**Comment by EliverLara** [comment] 2023-01-07 20:31
Hi, Could you check if it was fixed with the latest commit, please?

**Comment by Syphist** [comment] 2023-01-08 18:46
Hello, not the original issue opener but I just encountered this issue when updating my system. I decided to download the zip of the master branch to test it and I am getting some issues still, but it is less prevalent than before. I will upload a comparison of the stable version in the AUR vs the one I manually installed using the git version.

Stable version from AUR:
![image](https://user-images.githubusercontent.com/15790921/211213242-4ee2fa4c-fdf8-4ed4-8421-64a52e2fc6f9.png)

Git version:
![image](https://user-images.githubusercontent.com/15790921/211213308-7c4b3b46-cda6-49ad-a8d3-fc483726ef5c.png)

An odd thing to note is launching the screenshot tool makes it look dimmer, and switching to an adwaita theme gets rid of it temporarily. Not sure if that info helps, but it may help mitigate the issue for those that still want to use the theme while this is being fixed.

**Comment by meiseh** [comment] 2023-01-31 13:19
this happens to the window buttons applet and the tooltips as well.

can someone make a nice theme without rounded corners? i hate round corners.  :-) i already changed all the xpm's for the xfwm4 decoration part but just can't find where to look at all to find this panel issue.

**Comment by EliverLara** [comment] 2023-06-18 20:26
Fixed with c62a9a0ba92b933bd68b600bba39736a9bd605c6 :)

**Closed by EliverLara** 2023-06-18 20:26 UTC
